Creating a long format table with all LLM-generated scores:
- Read previously generated long format tables with RS scores and PC&BWS scores;
- normalize RS scores to [0,1];
- merge the two tables;
- Data inspection

In [ ]:
import pandas as pd

Read and inspect the data:

In [8]:
rs = pd.read_csv('rs/llm_rs_scores.csv')
# normalize the score to [0, 1]
rs['score'] = rs['score'] / 100
rs.head()

                 tweet_id  dimension method model  score
0  ['901760751152623616']    valence     rs   gpt   0.65
1  ['901760751152623616']    arousal     rs   gpt   0.58
2  ['901760751152623616']  dominance     rs   gpt   0.52
3  ['863364746577313792']    valence     rs   gpt   0.91
4  ['863364746577313792']    arousal     rs   gpt   0.87

In [ ]:
pc_bws = pd.read_csv('llm_pc_bws_scores.csv')
# Concatenate the dataframes
df = pd.concat([rs, pc_bws], ignore_index=True)

                 tweet_id  dimension method model  score
0  ['901760751152623616']    valence     rs   gpt   0.65
1  ['901760751152623616']    arousal     rs   gpt   0.58
2  ['901760751152623616']  dominance     rs   gpt   0.52
3  ['863364746577313792']    valence     rs   gpt   0.91
4  ['863364746577313792']    arousal     rs   gpt   0.87

In [ ]:
# count the unique values in each column except 'score'
for col in df.columns:
    if col != 'score':
        print(f"Unique values in column '{col}': {df[col].nunique()}")

# more necessary inspections can be added here

Unique values in column 'tweet_id': 100
Unique values in column 'dimension': 3
Unique values in column 'method': 3
Unique values in column 'model': 3

In [ ]:
# save the combined dataframe for later use
df.to_csv('llm_scores.csv', index=False)